docker_image:                                # [os.environ.get("BUILD_PLATFORM", "").startswith("linux") or (os.environ.get("CONFIG_VERSION", "1") == "1" and linux)]
   - quay.io/condaforge/linux-anvil-comp7    # [os.environ.get("BUILD_PLATFORM") == "linux-64" or (os.environ.get("CONFIG_VERSION", "1") == "1" and linux64)]
   - quay.io/condaforge/linux-anvil-cos7-x86_64    # [linux64]
 
   - quay.io/condaforge/linux-anvil-cuda:10.1       # [linux64 and (os.environ.get("BUILD_PLATFORM") == "linux-64" or os.environ.get("CONFIG_VERSION", "1") == "1")]
   - quay.io/condaforge/linux-anvil-cuda:10.2       # [linux64 and (os.environ.get("BUILD_PLATFORM") == "linux-64" or os.environ.get("CONFIG_VERSION", "1") == "1")]
   - quay.io/condaforge/linux-anvil-cuda:11.0       # [linux64 and (os.environ.get("BUILD_PLATFORM") == "linux-64" or os.environ.get("CONFIG_VERSION", "1") == "1")]
   - quay.io/condaforge/linux-anvil-cuda:11.1       # [linux64 and (os.environ.get("BUILD_PLATFORM") == "linux-64" or os.environ.get("CONFIG_VERSION", "1") == "1")]
   - quay.io/condaforge/linux-anvil-cuda:11.2       # [linux64 and (os.environ.get("BUILD_PLATFORM") == "linux-64" or os.environ.get("CONFIG_VERSION", "1") == "1")]

c_compiler_version:     # [linux]
  - 7                   # [linux64]
cxx_compiler_version:   # [linux]
  - 7                   # [linux64]

cuda_compiler:   # [linux64]
  - nvcc         # [linux64]

cuda_compiler_version:
  - None                       # [linux64]
  - None                       # [linux64]
  - 10.1                       # [linux64]
  - 10.2                       # [linux64 or win]
  - 11.0                       # [linux64 or win]
  - 11.1                       # [linux64 or win]
  - 11.2                       # [linux64 or win]

cdt_name:  # [linux]
  - cos6   # [linux64]
  - cos7   # [linux64]

  - cos6   # [linux64]
  - cos6   # [linux64]
  - cos7   # [linux64]
  - cos7   # [linux64]
  - cos7   # [linux64]

channel_targets:
  - conda-forge libcugraph_dev
