{% set name = "libcugraph" %}
{% set version = "21.06.00" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/rapidsai/cugraph/archive/refs/tags/v{{ version }}.tar.gz
    sha256: d6d88ebb68b4ceeb59e6eaf03f916b0ca138f0cf417428f01f2ab29c8761a68d
    folder: cugraph

build:
  number: 0
  skip: true  # [(not linux) or (cuda_compiler_version == "None")]
  run_exports:
    - {{ pin_subpackage(name, max_pin="x.x") }}
  missing_dso_whitelist:
    - '*/libcuda.*'

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}
    - cmake >=3.12.4
    - make
    - libgomp
  host:
    - boost-cpp
    - nccl
    - libfaiss =*=*_cuda
    - librmm ={{ version }}

test:
  commands:
    # Only testing for select headers and the library
    - test -f $PREFIX/include/cugraph/version_config.hpp
    - test -f $PREFIX/include/cugraph/algorithms.hpp
    - test -f $PREFIX/include/cugraph/graph.hpp
    - test -f $PREFIX/lib/libcugraph.so

about:
  home: https://github.com/rapidsai/cugraph
  license: Apache-2.0 AND BSD-3-Clause
  license_file:
    - cugraph/LICENSE
    - cugraph/cpp/build/gunrock/src/gunrock_ext/LICENSE.TXT
    - cugraph/cpp/build/_deps/raft-src/LICENSE
    - cugraph/cpp/build/_deps/cuco-src/LICENSE
    - cugraph/cpp/build/_deps/cuhornet-src/LICENSE
  summary: GPU accelerated graph algorithms

extra:
  recipe-maintainers:
    - rlratzel
    - leofang
