{% set name = "libcugraph" %}
{% set version = "0.19.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/rapidsai/cugraph/archive/refs/tags/v{{ version }}.tar.gz
    sha256: 047a0dc11a9783a759a7edcad8fe8d1729ca607e2ecdc3668a7f4533e0527a01
    folder: cugraph
  # libcugraph depends on the RMM header-only library of the same version.
  - url: https://github.com/rapidsai/rmm/archive/refs/tags/v{{ version }}.tar.gz
    sha256: eddd5b35b016d665eb4e8ea2dd31497d913b3e1eb831124e4cb27cba747267a0
    folder: rmm

build:
  number: 0
  skip: true  # [(not linux) or (cuda_compiler_version == "None")]
  run_exports:
    - {{ pin_subpackage(name, max_pin="x.x") }}
  missing_dso_whitelist:
    - "*/libcuda.*"

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}
    - cmake >=3.12.4
    - make
    - libgomp
  host:
    - boost-cpp
    - nccl
    - libfaiss =*=*_cuda
    - spdlog =1.7.0

test:
  commands:
    # Only testing for select headers and the library
    - test -f $PREFIX/include/cugraph/version_config.hpp
    - test -f $PREFIX/include/cugraph/algorithms.hpp
    - test -f $PREFIX/include/cugraph/graph.hpp
    - test -f $PREFIX/lib/libcugraph.so

about:
  home: https://github.com/rapidsai/cugraph
  license: Apache-2.0 AND BSD-3-Clause
  license_file:
    - cugraph/LICENSE
    - rmm/LICENSE
    - cugraph/cpp/build/gunrock/src/gunrock_ext/LICENSE.TXT
    - cugraph/cpp/build/_deps/raft-src/LICENSE
    - cugraph/cpp/build/_deps/thrust-src/LICENSE
    - cugraph/cpp/build/_deps/cuco-src/LICENSE
    - cugraph/cpp/build/_deps/cuhornet-src/LICENSE
  summary: 'GPU accelerated graph algorithms'

extra:
  recipe-maintainers:
    - rlratzel
    - leofang
